### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by nallath** [Spenbert02/FisnarRobotPlugin#11]
Just a suggestion, but instead of putting the .curapackages in the repo, you can also use the releases function of github. 

That way, you don't have to put all the curapackages in the repo. It also bundles the code nicely with it. If you want an example of how that looks, have a look at the Cura repository. As an added benefit, it also makes it easier to see what changed between versions.

**Comment by Spenbert02** [comment]
Ok, I think I'll do that. Putting the .curapackage files in the repo feels a little janky. Thanks
