### ISSUE TITLE
Properties generally don't need a "get" prefix

### ISSUE THREAD

**Issue by nallath** [Spenbert02/FisnarRobotPlugin#3]
I'm one of the Cura developers, and as part of our process for the marketplace we also review plugins. I've found a number of things that aren't blocking in any sense, but I figured I might as well share them with you!

So when looking at this code;
```python3
@pyqtProperty(int)
    def getNumExtruders(self):
```
I would suggest changing this to

```python3
@pyqtProperty(int)
    def num_extruders(self):
```

The rationale here is that by giving it the pyqtProperty decorator it behaves as if it's a property (and no longer like it's a function!). So semantically it's a bit weird to say object.getNumExtruders, as it implies that it's a slot / function being called (even though you don't entirely have the syntax of a function call). By changing it to have the same naming as a "regular" property would have, it makes a bit more sense (as in that case it would be object.num_extruders). 

It's not a big issue, but it might make it easier for you to maintain the code

**Comment by Spenbert02** [comment]
Thanks! That makes sense, using the 'get' prefix makes the qml syntax kind of awkward. I've changed all the pyqtProperty names.
