### ISSUE TITLE
PyqtProperties should have a notify property or be marked as constant

### ISSUE THREAD

**Issue by nallath** [Spenbert02/FisnarRobotPlugin#4]
If you take a look at this bit of code: https://github.com/Spenbert02/FisnarRobotPlugin/blob/27394fe661a2d4fda04f3e4925b355936529da0a/FisnarRobotExtension.py#L351-L356

You're using a PyqtProperty to figure out how many extruders are currently active. But PyqtProperties can either be "constant" or have a signal that is emitted when their value changes. 

For example:
```python3
@pyqtProperty(str, constant=True)
    def num_extruders(self):
```
This indicates that the property that it decorates will _never_ change value. The alternative is

```python3
numExtrudersChanged = pyqtSignal()
@pyqtProperty(int, notify=numExtudersChanged)
    def num_extruders(self):
```
In this case, you indicate that the value might change. The advantage of this is that if you use the property in QML and you emit the signal that it will automatically notify the qml objects that the value must be changed in the GUI as well. 

If you want some more examples of this, you can find them in the UM3NetworkPrinting plugin

**Comment by nallath** [comment]
In the case that the user can also change it, you often use the same property combined with a setter. An example of that can be seen here: 
https://github.com/Ultimaker/Cura/blob/9ca86c9d088979533fd2a0d12a7ecf2d3fa101fd/cura/Settings/GlobalStack.py#L344-L351

or

https://github.com/Ultimaker/Uranium/blob/0445f45e83bff39cd88fae51514db2171b57df8f/UM/Settings/Models/InstanceContainersModel.py#L168-L170

I personally only use the constant if it's some kind of value that can never change once it's instantiated. Another example of that can be found in the globalstack. 

https://github.com/Ultimaker/Cura/blob/9ca86c9d088979533fd2a0d12a7ecf2d3fa101fd/cura/Settings/GlobalStack.py#L168-L170

The object is created based on a config file, so the prefered files won't ever change after it's loaded.

Both options are fine of course, but qml does complain if you don't give it a notify or a constant property (so it's telling you to be explicit in which of the two options you want)

**Comment by Spenbert02** [comment]
Ok, I think I'm going to rewrite a unique setter for each property to clean things up a bit, similar to the second link you sent.

**Comment by Spenbert02** [comment]
Never mind, I figured it out.
